import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/Home.module.css";
import Navbar from "../components/Navbar";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ZooHoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Feed />
    </div>
  );
}
