import Navbar from "@/components/Navbar";
import Head from "next/head";
import NotificationScreen from "@/components/NotificationScreen";


const notifications = () => {
  return (
    <div>
    <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <NotificationScreen />
    </div>    
  )
}

export default notifications