import Navbar from "@/components/Navbar";
import Head from "next/head";



const notifications = () => {
  return (
    <div>
    <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>    
  )
}

export default notifications